sudo: true
dist: trusty


language: ruby
rvm:
  - 2.2.0

services:
  - docker

install:
  - docker pull jamo/tmc-sandbox
  - mkdir tmp/

script:
  - docker -v
  - docker help run
  - docker run -it --rm --cap-add=SYS_PTRACE --security-opt=apparmor:unconfined --privileged -v tmp:/dev/shm jamo/tmc-sandbox /bin/sh -c "cd tmc-sandbox/uml/ && ./run-test-exercise.sh"
