sudo: true
dist: trusty


language: ruby
rvm:
  - 2.2.0

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confnew install docker-engine


install:
  - docker pull jamo/tmc-sandbox
  - mkdir tmp/

script:
  - docker -v
  - docker help run
  - docker run -t --privileged --network="host" -p 3001:3001  -v tmp:/dev/shm jamo/tmc-sandbox /bin/sh -c "cd tmc-sandbox/uml/ && ./run-test-exercise.sh && tar xvf tmp/output.tar && find tmp/*.txt -print -exec cat {} \;"
  - docker run -t --privileged --network="host" -p 3001:3001  -v tmp:/dev/shm jamo/tmc-sandbox
  - curl 127.0.0.1:3001/status.json
  - sleep 20 && curl 127.0.0.1:3001/status.json
