sudo: true
dist: trusty


language: ruby
rvm:
  - 2.2.0

services:
  - docker

install:
  - docker pull jamo/tmc-sandbox
  - mkdir tmp/

script:
  - docker -v
  - docker help run
  - docker run -d --privileged  -p 3001:3001 -v tmp:/dev/shm jamo/tmc-sandbox
  - sleep 20 && curl 127.0.0.1:3001/status.json
